"""
Core module - Data models, base classes, and shared utilities.

This module provides the foundational components for building trading strategies:

Data Models:
    - PriceData: Real-time price information for a market
    - Candlestick: OHLCV candlestick data
    - Order: Order representation with status tracking
    - OrderSignal: Signal generated by strategy to place an order
    - Position: Position tracking for a single token
    - TradeResult: Trade execution result

Enums:
    - OrderStatus: Order lifecycle states (PENDING, FILLED, CANCELLED, REJECTED)
    - OrderType: Order types (GTC, FOK)
    - TradeSide: Trade direction (BUY, SELL)
    - TokenType: Token type (YES/NO or UP/DOWN)

Market Events:
    - MarketStart: Market opened/subscribed event
    - MarketEnd: Market closed event
    - MarketSettled: Market settlement event with winner

Strategy Framework:
    - BaseStrategy: Abstract base class for all trading strategies
    - register_strategy(): Decorator to register a strategy class
    - get_strategy_registry(): Get all registered strategies

Configuration:
    - Config: Main configuration class with all settings
    - load_config(): Load configuration from file/environment

Example:
    >>> from polymoney.core import BaseStrategy, register_strategy
    >>> from polymoney.core import PriceData, OrderSignal, TradeSide, TokenType
    >>> 
    >>> @register_strategy("my-strategy")
    ... class MyStrategy(BaseStrategy):
    ...     @property
    ...     def strategy_type(self) -> str:
    ...         return "custom"
    ...     
    ...     def on_price_update(self, price_data: PriceData) -> list[OrderSignal]:
    ...         # Your trading logic here
    ...         return []
"""

from .models import (
    # Core data models
    PriceData,
    Candlestick,
    Order,
    OrderSignal,
    Position,
    PositionPair,
    TradeResult,
    PerformanceMetrics,
    # Market events
    MarketStart,
    MarketEnd,
    MarketSettled,
    # Enums
    OrderStatus,
    OrderType,
    TradeSide,
    TokenType,
    StrategyState,
)
from .strategy import (
    BaseStrategy,
    register_strategy,
    get_strategy_registry,
    list_strategies,
    get_strategy_class,
    create_strategy,
)
from .config import Config, load_config
from .logging import get_logger, setup_logging

__all__ = [
    # Data Models
    "PriceData",
    "Candlestick",
    "Order",
    "OrderSignal",
    "Position",
    "PositionPair",
    "TradeResult",
    "PerformanceMetrics",
    # Market Events
    "MarketStart",
    "MarketEnd",
    "MarketSettled",
    # Enums
    "OrderStatus",
    "OrderType",
    "TradeSide",
    "TokenType",
    "StrategyState",
    # Strategy Framework
    "BaseStrategy",
    "register_strategy",
    "get_strategy_registry",
    "list_strategies",
    "get_strategy_class",
    "create_strategy",
    # Configuration
    "Config",
    "load_config",
    # Logging
    "get_logger",
    "setup_logging",
]
