"""
Core data models for Polymoney.

All models use Pydantic for validation and serialization.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field


# Enums
class TradeSide(str, Enum):
    """Trade side (buy or sell)."""

    BUY = "buy"
    SELL = "sell"


class TokenType(str, Enum):
    """Token type in a binary market."""

    YES = "yes"
    NO = "no"
    UP = "up"
    DOWN = "down"


class OrderStatus(str, Enum):
    """Order status lifecycle."""

    PENDING = "pending"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class OrderType(str, Enum):
    """Order type."""

    GTC = "GTC"  # Good-Till-Cancelled
    GTD = "GTD"  # Good-Till-Date
    FOK = "FOK"  # Fill-Or-Kill
    FAK = "FAK"  # Fill-And-Kill (IOC)


class StrategyState(str, Enum):
    """Strategy lifecycle states."""

    INITIALIZED = "initialized"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"


# Market Data Models
class PriceData(BaseModel):
    """Real-time price update from market data service."""

    market_id: str = Field(description="Market condition ID")
    up_price: float = Field(ge=0, le=1, description="YES/UP token best price")
    down_price: float = Field(ge=0, le=1, description="NO/DOWN token best price")
    timestamp: datetime = Field(default_factory=datetime.now, description="Price timestamp")
    spread: float = Field(default=0, ge=0, description="Bid-ask spread")
    up_ask_size: Optional[float] = Field(default=None, description="Top-of-book ask size for UP")
    down_ask_size: Optional[float] = Field(default=None, description="Top-of-book ask size for DOWN")

    model_config = ConfigDict(ser_json_timedelta="iso8601")

    @property
    def mid_price(self) -> float:
        """Calculate mid price."""
        return (self.up_price + self.down_price) / 2


class Candlestick(BaseModel):
    """OHLCV candlestick data."""

    market_id: str = Field(description="Market condition ID")
    interval: str = Field(description="Candlestick interval (1m, 5m, 15m, 1h, 4h, 1d)")
    timestamp: datetime = Field(description="Interval start time")
    token_type: TokenType = Field(description="Token type (YES/NO)")
    open: float = Field(ge=0, le=1, description="Opening price")
    high: float = Field(ge=0, le=1, description="Highest price")
    low: float = Field(ge=0, le=1, description="Lowest price")
    close: float = Field(ge=0, le=1, description="Closing price")
    volume: float = Field(ge=0, description="Trading volume")

    model_config = ConfigDict(ser_json_timedelta="iso8601")


# Order Models
class OrderSignal(BaseModel):
    """Signal generated by a strategy to place an order."""

    side: TradeSide = Field(description="Buy or sell")
    token_type: TokenType = Field(default=TokenType.YES, description="Token type")
    target_price: float = Field(ge=0, le=1, description="Target limit price")
    size: float = Field(gt=0, description="Order size in shares")
    order_type: OrderType = Field(default=OrderType.GTC, description="Order type (GTC/FOK/FAK)")
    is_taker: bool = Field(default=False, description="Whether this is a taker order")

    model_config = ConfigDict(use_enum_values=True)


class Order(BaseModel):
    """Order representation."""

    order_id: str = Field(description="Unique order ID")
    strategy_id: str = Field(description="Strategy that created the order")
    market_id: str = Field(description="Market condition ID")
    side: TradeSide = Field(description="Buy or sell")
    token_type: TokenType = Field(description="Token type (YES/NO)")
    price: float = Field(ge=0, le=1, description="Limit price")
    size: float = Field(gt=0, description="Order size in shares")
    filled_size: float = Field(default=0, ge=0, description="Filled amount")
    status: OrderStatus = Field(default=OrderStatus.PENDING, description="Order status")
    order_type: OrderType = Field(default=OrderType.GTC, description="Order type")
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    expiration: Optional[datetime] = Field(default=None, description="Expiration for GTD orders")

    @property
    def remaining_size(self) -> float:
        """Calculate remaining unfilled size."""
        return self.size - self.filled_size

    @property
    def is_complete(self) -> bool:
        """Check if order is fully filled or terminal."""
        return self.status in (OrderStatus.FILLED, OrderStatus.CANCELLED, OrderStatus.REJECTED)

    model_config = ConfigDict(use_enum_values=True)


# Position Models
class Position(BaseModel):
    """Position tracking for a single token type."""

    shares: float = Field(default=0, ge=0, description="Number of shares held")
    cost: float = Field(default=0, ge=0, description="Total cost basis")

    @property
    def avg_price(self) -> float:
        """Calculate average price per share."""
        return self.cost / self.shares if self.shares > 0 else 0.0

    def add(self, shares: float, price: float) -> None:
        """Add shares to position."""
        self.shares += shares
        self.cost += shares * price

    def reset(self) -> None:
        """Reset position to zero."""
        self.shares = 0.0
        self.cost = 0.0


class PositionPair(BaseModel):
    """Position pair for a binary market (UP/DOWN or YES/NO)."""

    up: Position = Field(default_factory=Position)
    down: Position = Field(default_factory=Position)

    @property
    def hedged_position(self) -> float:
        """Get the hedged (minimum) position size."""
        return min(self.up.shares, self.down.shares)

    @property
    def unhedged_shares(self) -> float:
        """Get the unhedged (risk) exposure."""
        return abs(self.up.shares - self.down.shares)

    @property
    def total_cost(self) -> float:
        """Get total cost of both positions."""
        return self.up.cost + self.down.cost


# Trade Models
class TradeResult(BaseModel):
    """Result of a trade execution."""

    trade_id: str = Field(description="Unique trade ID")
    order_id: str = Field(description="Associated order ID")
    strategy_id: str = Field(description="Strategy ID")
    market_id: str = Field(description="Market condition ID")
    side: TradeSide = Field(description="Buy or sell")
    token_type: TokenType = Field(description="Token type")
    price: float = Field(ge=0, le=1, description="Execution price")
    size: float = Field(gt=0, description="Trade size")
    timestamp: datetime = Field(default_factory=datetime.now)
    mode: str = Field(default="paper", description="Trading mode (paper/live)")

    model_config = ConfigDict(use_enum_values=True)


# Market Event Models
class MarketStart(BaseModel):
    """Market start event."""

    market_id: str = Field(description="Market condition ID")
    title: str = Field(default="", description="Market title/question")
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(ser_json_timedelta="iso8601")


class MarketEnd(BaseModel):
    """Market end (close) event."""

    market_id: str = Field(description="Market condition ID")
    timestamp: datetime = Field(default_factory=datetime.now)
    final_up_price: Optional[float] = Field(default=None, description="Final UP/YES price")
    final_down_price: Optional[float] = Field(default=None, description="Final DOWN/NO price")

    model_config = ConfigDict(ser_json_timedelta="iso8601")


class MarketSettled(BaseModel):
    """Market settlement event."""

    market_id: str = Field(description="Market condition ID")
    winner: TokenType = Field(description="Winning outcome (UP/DOWN or YES/NO)")
    timestamp: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(use_enum_values=True)


# Performance Metrics
class PerformanceMetrics(BaseModel):
    """Strategy performance metrics."""

    strategy_id: str = Field(description="Strategy ID")
    total_pnl: float = Field(default=0, description="Total profit/loss")
    realized_pnl: float = Field(default=0, description="Realized P&L")
    unrealized_pnl: float = Field(default=0, description="Unrealized P&L")
    trade_count: int = Field(default=0, ge=0, description="Number of trades")
    win_count: int = Field(default=0, ge=0, description="Number of winning trades")
    loss_count: int = Field(default=0, ge=0, description="Number of losing trades")
    max_drawdown: float = Field(default=0, ge=0, description="Maximum drawdown")

    @property
    def win_rate(self) -> float:
        """Calculate win rate."""
        total = self.win_count + self.loss_count
        return self.win_count / total if total > 0 else 0.0
